"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GET_CARD_REDIRECT = "GET_CARD_REDIRECT";
exports.SET_CLIENT_TOKEN = "GET_CLIENT_TOKEN";
exports.SET_HOSTED_FIELDS_PROVIDER_CLIENT = "SET_HOSTED_FIELDS_PROVIDER_CLIENT";
exports.SET_PROVIDER_CLIENT = "SET_PROVIDER_CLIENT";
exports.SET_3DS_PROVIDER_CLIENT = "SET_3DS_PROVIDER_CLIENT";
exports.SET_DROP_IN_PROVIDER_CLIENT = "SET_DROP_IN_PROVIDER_CLIENT";
exports.SET_CARD_DATA_MODEL = "SET_CARD_DATA_MODEL";
exports.SET_PROVIDER_CONFIGURATION = "SET_PROVIDER_CONFIGURATION";
exports.SET_APP_LOADING_STATE = "SET_APP_LOADING_STATE";
exports.SET_CURRENT_ACTION = "SET_CURRENT_ACTION";
exports.SET_POPUP_MESSAGE = "SET_POPUP_MESSAGE";
exports.SET_POPUP_MESSAGE_TYPE = "SET_POPUP_MESSAGE_TYPE";
exports.SET_ACS_CHALLENGE_DATA = "SET_ACS_CHALLENGE_DATA";
//# sourceMappingURL=mutation-types.js.map