export const GET_CARD_REDIRECT = "GET_CARD_REDIRECT";
export const SET_CLIENT_TOKEN = "GET_CLIENT_TOKEN";
export const SET_HOSTED_FIELDS_PROVIDER_CLIENT = "SET_HOSTED_FIELDS_PROVIDER_CLIENT";
export const SET_PROVIDER_CLIENT = "SET_PROVIDER_CLIENT";
export const SET_3DS_PROVIDER_CLIENT = "SET_3DS_PROVIDER_CLIENT";
export const SET_DROP_IN_PROVIDER_CLIENT = "SET_DROP_IN_PROVIDER_CLIENT";
export const SET_CARD_DATA_MODEL = "SET_CARD_DATA_MODEL";
export const SET_PROVIDER_CONFIGURATION = "SET_PROVIDER_CONFIGURATION";
